server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doglover?serverTimezone=UTC&characterEncoding=UTF-8
    username: doglover
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: SpringBootJPAHikariCP
      maximum-pool-size: 2
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 28770000
      connection-init-sql: set wait_timeout = 600
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        default_batch_size: 1000
        show_sql: false
        format_sql: true

logging:
  level:
#    root: warn
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    kr.co.doglove.doglove.mapper: trace;

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.co.doglove.doglove.domain
